type: systemd
system:
  enabled:
  #  - tailscaled.service # Enabled (runs on system boot)
    - com.system76.Scheduler.service
    - libvirtd.service
   # - custom-cockpit.service
    - cockpit.socket
    - sshd
    - virtxend.service
    - virtxend.socket
