# image will be published to ghcr.io/<user>/<name>
name: myarcade
# description will be included in the image's metadata
description: "myOS is an operating system dedicated to being user-friendly and progressive "

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/bazzite-htpc-gnome
image-version: latest # is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - from-file: common/common-files.yml
  - from-file: common/gnome-flatpaks.yml
  - from-file: common/tailscale.yml
  - from-file: common/gnome-extensions.yml
  - from-file: common/gnome-files.yml
