type: rpm-ostree
  repos: # - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
  install:
    - podman-compose
  remove:
    # example: removing firefox (in favor of the flatpak)
    # "firefox" is the main package, "firefox-langpacks" is a dependency
    - firefox
    - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)
