  type: rpm-ostree 
  repos: 
    - https://copr.fedorainfracloud.org/coprs/kylegospo/bazzite-multilib/repo/fedora-39/kylegospo-bazzite-multilib-fedora-39.repo
    - https://copr.fedorainfracloud.org/coprs/kylegospo/bazzite/repo/fedora-39/kylegospo-bazzite-fedora-39.repo
    - https://copr.fedorainfracloud.org/coprs/kylegospo/system76-scheduler/repo/fedora-39/kylegospo-system76-scheduler-fedora-39.repo
    - https://copr.fedorainfracloud.org/coprs/ublue-os/staging/repo/fedora-39/ublue-os-staging-fedora-39.repo
    - https://copr.fedorainfracloud.org/coprs/ublue-os/bling/repo/fedora-39/ublue-os-bling-fedora-39.repo
  install:
    - joystickwake
    - mangohud
    - system76-scheduler
    - ublue-update
