  type: rpm-ostree 
  repos: 
    - https://copr.fedorainfracloud.org/coprs/kylegospo/bazzite-multilib/repo/fedora-39/kylegospo-bazzite-multilib-fedora-39.repo
    - https://copr.fedorainfracloud.org/coprs/kylegospo/bazzite/repo/fedora-39/kylegospo-bazzite-fedora-39.repo
    - https://copr.fedorainfracloud.org/coprs/kylegospo/prompt/repo/fedora-39/kylegospo-prompt-fedora-39.repo
  install:
    - joystickwake
    - mangohud
    - ptyxis
