type: default-flatpaks
system:
install:
  - org.gnome.Calculator
  - org.gnome.Characters
  - org.gnome.Evince
  - org.gnome.FileRoller
  - org.gnome.NautilusPreviewer
  - org.gnome.TextEditor
  - org.gnome.clocks
  - org.gnome.font-viewer
  - org.gnome.Decibels
  - io.github.celluloid_player.Celluloid
  - io.github.vikdevelop.SaveDesktop
  - com.mattjakeman.ExtensionManager
  remove:
  - org.gnome.Contacts
  - org.gnome.Weather
  - org.gnome.Maps
  - com.github.GradienceTeam.Gradience
