type: rpm-ostree
repos: 
  - https://copr.fedorainfracloud.org/coprs/astrawan/gnome-shell-extensions/repo/fedora-39/astrawan-gnome-shell-extensions-fedora-39.repo
install:
  - gnome-shell-extension-gsconnect
  - gnome-shell-extension-appindicator
  - gnome-shell-extension-blur-my-shell
  - gnome-shell-extension-user-theme
  - gnome-shell-extension-caffeine
  - gnome-shell-extension-drive-menu
  - gnome-shell-extension-forge
  - gnome-randr-rust
  - gnome-shell-extension-tailscale-gnome-qs
  - gnome-shell-extension-vitals
remove:
  - yelp
  - gnome-tour
  - gnome-system-monitor
