type: rpm-ostree
install:
  - gnome-shell-extension-gsconnect
  - gnome-shell-extension-appindicator
  - gnome-shell-extension-blur-my-shell
  - gnome-shell-extension-system76-scheduler
  - gnome-shell-extension-user-theme
  - gnome-shell-extension-caffeine
  - gnome-shell-extension-vitals
  - gnome-shell-extension-drive-menu
  - gnome-shell-extension-forge
