type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      # If no repo information is specified, Flathub will be used by default
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-name: flathub
      repo-title: "Flathub (system-wide)"
install:
  - org.gnome.Calculator
  - org.gnome.Characters
  - org.gnome.Evince
  - org.gnome.FileRoller
  - org.gnome.NautilusPreviewer
  - org.gnome.TextEditor
  - org.gnome.clocks
  - org.gnome.font-viewer
  - io.github.vikdevelop.SaveDesktop
  - com.mattjakeman.ExtensionManager
  - io.github.dvlv.boxbuddyrs
  - dev.deedles.Trayscale
  - io.github.flattool.Warehouse
  - com.github.tchx84.Flatseal
  - it.mijorus.gearlever
  - com.usebottles.bottles
  - com.github.marhkb.Pods
  - dev.skynomads.Seabird
  - net.nokyan.Resources
  - fr.sgued.ten_forward
  - com.leinardi.gst
  - org.libreoffice.LibreOffice
  - page.codeberg.libre_menu_editor.LibreMenuEditor
  - org.gnome.Decibels
  - io.github.celluloid_player.Celluloid
remove:
  - io.missioncenter.MissionCenter
  - org.gnome.Contacts
  - org.gnome.Weather
  - org.gnome.Maps
  - com.github.GradienceTeam.Gradience
