type: rpm-ostree
repos: 
- https://copr.fedorainfracloud.org/coprs/solopasha/hyprland/repo/fedora-39/solopasha-hyprland-fedora-39.repo
- https://copr.fedorainfracloud.org/coprs/principis/zrepl/repo/fedora-39/principis-zrepl-fedora-39.repo
install: 
# Simple Desktop Display Manager
- sddm
- sddm-themes
- qt5-qtgraphicaleffects
- qt5-qtquickcontrols2
- qt5-qtsvg
# Hyprland & Tools
- hyprland
- hyprnome
- hyprlock
- hypridle
- hyprpicker
- hyprland-plugins
- pyprland
- aylurs-gtk-shell
- swww
- waypaper
- xdg-desktop-portal-hyprland
- wl-clipboard
- brightnessctl
