modules:
  - type: files
    files:
      - homedir: /hyprland/usr/etc/homedir
      - usr: /hyprland/usr # copy static configurations
                  # configuration you wish to end up in /etc/ on the booted system should be
                  # added into /usr/etc/ as that is the proper "distro" config directory on ostree
                  # read more in the files module's README
