type: rpm-ostree
repos: 
- https://copr.fedorainfracloud.org/coprs/solopasha/hyprland/repo/fedora-39/solopasha-hyprland-fedora-39.repo
- https://copr.fedorainfracloud.org/coprs/principis/zrepl/repo/fedora-39/principis-zrepl-fedora-39.repo
install: 
  - hyprnome
  - hyprlock
  - hypridle
  - hyprpicker
  - hyprland-plugins
  - pyprland
  - aylurs-gtk-shell
  - swww
  - waypaper
