type: rpm-ostree
repos: 
- https://copr.fedorainfracloud.org/coprs/solopasha/hyprland/repo/fedora-39/solopasha-hyprland-fedora-39.repo
install: 
- hyprland
- hyprnome
- hyprlock
- hypridle
- swww
- waypaper
- hyprland-plugins
- pyprland
- eww-git
- xdg-desktop-portal-hyprland
- wl-clipboard
- brightnessctl
