set allow-duplicate-recipes := true
set ignore-comments := true

_default:
    #!/usr/bin/bash
    source /usr/lib/ujust/libformatting.sh
    echo "$(Urllink "https://universal-blue.discourse.group/docs?topic=42" "Click here to view the Universal Blue just documentation")"
    /usr/bin/ujust --list --list-heading $'Available commands:\n' --list-prefix $' - '

# Imports
import "/usr/share/ublue-os/just/00-default.just"
import "/usr/share/ublue-os/just/10-update.just"
import "/usr/share/ublue-os/just/20-clean.just"
import "/usr/share/ublue-os/just/30-distrobox.just"
import "/usr/share/ublue-os/just/31-toolbox.just"
import "/usr/share/ublue-os/just/40-nvidia.just"
import "/usr/share/ublue-os/just/50-akmods.just"
import "/usr/share/ublue-os/just/60-custom.just"
import "/usr/share/ublue-os/just/80-myos.just"
import "/usr/share/ublue-os/just/81-myos-fixes.just"
import "/usr/share/ublue-os/just/82-myos-apps.just"
import "/usr/share/ublue-os/just/82-myos-sunshine.just"
import "/usr/share/ublue-os/just/82-myos-waydroid.just"
import "/usr/share/ublue-os/just/83-myos-audio.just"
import "/usr/share/ublue-os/just/84-myos-virt.just"
