name: myOS-builder
on:
  schedule:
    - cron: "00 18 * * *" # build at 18:00 UTC every day 
                          # 80 minutes after the last uBlue images start building
                          # 60 minutes after last wayblue images start building
  push:
    paths-ignore: # don't rebuild if only documentation has changed
      - "**.md"
      
  pull_request:
  workflow_dispatch: # allow manually triggering builds
jobs:
  bluebuild:
    name: Build myOS
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      fail-fast: false # stop GH from cancelling all matrix builds if one fails
      matrix:
        recipe:
          - recipes/intel-amd/gnome.yml
          - recipes/intel-amd/kde.yml
          - recipes/intel-amd/hyprland.yml
          - recipes/intel-amd/cosmic.yml
          - recipes/intel-amd/myarcade.yml
          - recipes/intel-mac/gnome.yml
          - recipes/intel-mac/kde.yml
          - recipes/intel-mac/hyprland.yml
          - recipes/intel-mac/cosmic.yml
    steps:
       # the build is fully handled by the reusable github action
      - name: Build myOS
        uses: blue-build/github-action@v1.4
        with:
          recipe: ${{ matrix.recipe }}
          cosign_private_key: ${{ secrets.SIGNING_SECRET }}
          registry_token: ${{ github.token }}
          pr_event_number: ${{ github.event.number }}
          use_unstable_cli: true
